"""add page_revision table

Revision ID: 1cc96e2c81a7
Revises: e9d30f353061
Create Date: 2026-07-12 12:40:41.502834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc96e2c81a7'
down_revision = 'e9d30f353061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_revision',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('seo', sa.JSON(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_revision_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_revision_page_id'), ['page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_revision_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_revision_deleted_at'))

    op.drop_table('page_revision')
    # ### end Alembic commands ###
