"""faq + partners

Revision ID: 2146e36bf295
Revises: 4e304affd5e7
Create Date: 2026-07-11 13:19:00.646692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2146e36bf295'
down_revision = '4e304affd5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_is_published'), ['is_published'], unique=False)

    op.create_table('partner',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_is_published'))
        batch_op.drop_index(batch_op.f('ix_partner_deleted_at'))

    op.drop_table('partner')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_is_published'))
        batch_op.drop_index(batch_op.f('ix_faq_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_faq_category'))

    op.drop_table('faq')
    # ### end Alembic commands ###
