"""content modules (article, category, testimonial, team, brand, document, event)

Revision ID: 42a711b495eb
Revises: 502d134d19d3
Create Date: 2026-07-11 19:24:08.618802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a711b495eb'
down_revision = '502d134d19d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=400), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_status'), ['status'], unique=False)

    op.create_table('brand',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('logo', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_is_published'), ['is_published'], unique=False)

    op.create_table('category',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=False)

    op.create_table('document',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=400), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_is_published'), ['is_published'], unique=False)

    op.create_table('event',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('cover_image', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_status'), ['status'], unique=False)

    op.create_table('team_member',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('photo', sa.String(length=400), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_is_published'), ['is_published'], unique=False)

    op.create_table('testimonial',
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=400), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testimonial_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_testimonial_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testimonial_is_published'))
        batch_op.drop_index(batch_op.f('ix_testimonial_deleted_at'))

    op.drop_table('testimonial')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_is_published'))
        batch_op.drop_index(batch_op.f('ix_team_member_deleted_at'))

    op.drop_table('team_member')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_status'))
        batch_op.drop_index(batch_op.f('ix_event_starts_at'))
        batch_op.drop_index(batch_op.f('ix_event_slug'))
        batch_op.drop_index(batch_op.f('ix_event_is_featured'))
        batch_op.drop_index(batch_op.f('ix_event_deleted_at'))

    op.drop_table('event')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_is_published'))
        batch_op.drop_index(batch_op.f('ix_document_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_document_category'))

    op.drop_table('document')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))
        batch_op.drop_index(batch_op.f('ix_category_is_published'))
        batch_op.drop_index(batch_op.f('ix_category_deleted_at'))

    op.drop_table('category')
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_is_published'))
        batch_op.drop_index(batch_op.f('ix_brand_deleted_at'))

    op.drop_table('brand')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_status'))
        batch_op.drop_index(batch_op.f('ix_article_slug'))
        batch_op.drop_index(batch_op.f('ix_article_section'))
        batch_op.drop_index(batch_op.f('ix_article_is_featured'))
        batch_op.drop_index(batch_op.f('ix_article_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_article_category'))

    op.drop_table('article')
    # ### end Alembic commands ###
