"""pages (page builder)

Revision ID: bffe59074d0d
Revises: 2146e36bf295
Create Date: 2026-07-11 18:58:09.748975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffe59074d0d'
down_revision = '2146e36bf295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('seo', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_status'))
        batch_op.drop_index(batch_op.f('ix_page_slug'))
        batch_op.drop_index(batch_op.f('ix_page_locale'))
        batch_op.drop_index(batch_op.f('ix_page_deleted_at'))

    op.drop_table('page')
    # ### end Alembic commands ###
