"""settings + menus

Revision ID: e9d30f353061
Revises: 42a711b495eb
Create Date: 2026-07-11 20:37:57.565205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d30f353061'
down_revision = '42a711b495eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_location'), ['location'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_setting_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_setting_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_key'))
        batch_op.drop_index(batch_op.f('ix_setting_group'))
        batch_op.drop_index(batch_op.f('ix_setting_deleted_at'))

    op.drop_table('setting')
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_location'))
        batch_op.drop_index(batch_op.f('ix_menu_deleted_at'))

    op.drop_table('menu')
    # ### end Alembic commands ###
